### ISSUE TITLE
how does this compare so bos? apart from being simpler

### ISSUE THREAD

**Issue by keblek** [RooSoft/igniter#1]
curious if you have seen this 
https://github.com/alexbosworth/balanceofsatoshis

**Comment by RooSoft** [comment]
BOS has an automatic route finder to rebalance your own channels. You feed it with an input and an output channel, it will try to figure out a route that makes it possible and will then proceed with the rebalancement.

Igniter is useful when you have a specific route in mind. It should be provided with the whole route to do its work.

**Comment by keblek** [comment]
cool! will keep an eye on this and try it out later
