### ISSUE TITLE
Check for dependencies fails on umbrel

### ISSUE THREAD

**Issue by StijnBTC** [RooSoft/igniter#12]
Lncli is not available on umbrel because it uses Docker. Now the check dependencies fails. Maybe the $LNCLI can be used in the dependencies array instead of "lncli"

**Comment by RooSoft** [comment]
Great point, will check this out closely... thanks!

**Comment by RooSoft** [comment]
On umbrel, ignore lncli dependency as it is obviously there

**Comment by Hans-Wurst-21** [comment]
Hello, how can I bypass the dependency with Citadel?  I get the error "Tool missing: lncli".  Thank you for your help :)

**Comment by RooSoft** [comment]
`lncli` is the LND app that igniter uses... if not available, igniter can't access the lightning node. Check the Citadel documentation for more info about this.
