### ISSUE TITLE
automatic amount

### ISSUE THREAD

**Issue by vv01f** [RooSoft/igniter#14]
(manual amount still could be set via option or in a ring/swap file)
next value stilll set manually …

rough idea:

```
# value in satoshis to transmit
# local_balance
LOCAL_BALANCE=$($LNCLI listchannels | jq -cr '.channels[] | { remote_pubkey, local_balance } | select( .remote_pubkey == "'${FIRST_PUBKEY}'" ) | { local_balance } | flatten | .[0]' )
REMOTE_BALANCE=$($LNCLI listchannels | jq -cr '.channels[] | { remote_pubkey, remote_balance } | select( .remote_pubkey == "'${FIRST_PUBKEY}'" ) | { remote_balance } | flatten | .[0]' )
CAPACITY=$($LNCLI listchannels | jq -cr '.channels[] | { remote_pubkey, capacity } | select( .remote_pubkey == "'${FIRST_PUBKEY}'" ) | { capacity } | flatten | .[0]' )
#AMOUNT=10000000
if test ${REMOTE_BALANCE} -eq 0 ; then
# +1 to secure that one of two parties trying to balance half will fail
        AMOUNT=$(( ${LOCAL_BALANCE} / 2 + 1 ))
else
        >&2 printf "error: remote non zero on first peer\n"
        exit 3
fi
```
is there a good reason to balance `$CAPACITY / 2` instead or to go with another non-custom number as default?

**Comment by RooSoft** [comment]
Can you give a little more context about this issue? That code doesn't seem to be either in the current version of Igniter, or in any pull request.

**Comment by vv01f** [comment]
The purpose is to have less reason for editing the script file. So besides the other issue about the peers public keys the amount was another value that needs editing… usually the amount to be balanced is supposed to be 50% of total … as there is not full capacity available I wanted to know if we take capacity nevertheless or the available (local) balance?

Gladly will push a PR when everything is cleared, just giving you and maybe others the opportunity to throws in a thought or two.

**Comment by RooSoft** [comment]
Depends... the original idea was to balance channels 50%. Nobody knows if somebody uses the script for other purposes. Locking the amount in the script would limit the script's usefulness as well as add some extra code.

**Comment by RooSoft** [comment]
Same comments as #15 

The aim here is to keep Igniter small and simple.

If anybody wants to improve the software by adding features, you're welcome to fork it.

Since this issue hasn't got any traction in more than two months, it will be closed.

Thank you @vv01f for the suggestion!
