### ISSUE TITLE
file for rings/swaps also considering policy

### ISSUE THREAD

**Issue by vv01f** [RooSoft/igniter#15]
when opening several rings in a short period of time it'd be nice to handle then separately in files instead of editing the script

format per line: `key: value`

I for now added lines for following keys 
* members (comma separated list first_peer,…,own_peer … number of peers can be determined e.g. by count of commas+1)
* capacity (optional, can be read from listchannel)
* url (informational where a channel might be documented, e.g. <lightningnetwork.plus> )
* policy_base (policy for base_fee_msat)
* policy_min_htlc (policy for min_htlc_msat)
* policy_fee_rate (policy for fee_rate)

any thoughts what else would be useful, also to automate the whole ring building and initial balancing as well as keeping additional information?

**Comment by RooSoft** [comment]
That was my original thought, but it has been decided to keep it all in one file, as file parsing could just by itself be consisted of more code than the whole current script.

**Comment by RooSoft** [comment]
If you can manage to do something reusable, simple and stable, feel free to suggest a pull request.

**Comment by RooSoft** [comment]
The aim here is to keep Igniter small and simple.

Nothing prevents from copying the script with different configurations as it is.

Since this issue hasn't got any traction in more than two months, it will be closed.

Thank you @vv01f for the suggestion!
