### ISSUE TITLE
No matching outgoing channel

### ISSUE THREAD

**Issue by dragsugg** [RooSoft/igniter#16]
Although there is a channel, this error message appears:

[lncli] rpc error: code = Unknown desc = no matching outgoing channel available for node 2 (pubkey)

On 1ml.com or amboss.space the channel is listed.

**Comment by SpencerPearson** [comment]
try to lower the amount you're sending and rebuild. Sometimes a channel will have a crazy high fee that will cause routing to fail; that's what's happening to me right now

**Comment by ziggie1984** [comment]
This is definitely no igniter issue, I was able to build the route with my own script and it worked just fine (https://github.com/ziggie1984/miscellanous/blob/e83fbf689f7ca06d256d65e0f5330b10496470b2/igniter2_0.js)

I think the problem lies in the BuildRoute grpc call

**Comment by RooSoft** [comment]
Thanks guys, closing this issue...
