### ISSUE TITLE
cant create ring...

### ISSUE THREAD

**Issue by jcbelair** [RooSoft/igniter#19]
I am trying to create a ring between 12 parties.. Most Umbrel, mine Nodl.... We have tried to run the script (2 files, one config, one sh) and keep getting these errors... we tried from different nodes (changing the node order in the config file).
Ran out of ideas now..

bitcoin@nodl:~/igniter$ ./igniter.sh build
[lncli] rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: context deadline exceeded"
bitcoin@nodl:~/igniter$ ./igniter.sh send
[lncli] rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: context deadline exceeded"
[lncli] rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: context deadline exceeded"
Route fee is 0 sats.
[lncli] payment hash must be exactly 32 bytes, is instead 0

Any idea? 

thanks

**Comment by RooSoft** [comment]
Well, there seems to be a timeout between two nodes...

This script merely returns what `lnd` outputs... unfortunately, the error message doesn't mention which nodes cause that problem, so there's little that can be done here else than make sure that every ring participant are correctly connected between each other.

On a side note, the larger the ring, higher the chances of meeting such problems. 12 might be the biggest ring I have heard about yet.
