### ISSUE TITLE
Lnci LND Error on Citadel

### ISSUE THREAD

**Issue by SiriusLightning21** [RooSoft/igniter#22]
I dont know if it is an issue or the problem is why I use Citadel. 
My problem is.
I use Igniter 1.0.3 on Citadel with Version 0.1.3. In Igniter there is a specific Code for Umbrel user and this dont work on Citadel. I changed every word from umbrel to citadel but this did not help.
Is there a way I could use the newest Version of Igniter with Citadel because the Igniter version in Lightning Shell is outdated?

**Comment by RooSoft** [comment]
Where can I find Citadel documentation about how to interact with bitcoin core on such a node?

**Comment by RooSoft** [comment]
Figuring out [right here](https://github.com/runcitadel/core/blob/f0bfc3158aa477671dc22361b03d1545396dbcd3/docker-compose.yml#L68) that it's using Docker, but I would need more info about what's in the image.

**Comment by AaronDewes** [comment]
Similar to Umbrel, you can check for `$HOME/citadel` to see  it's Citadel, then use `docker exec -i lightning lncli` as lncli.

**Comment by RooSoft** [comment]
I don't have a Citadel yet, so if someone is willing to make a PR and attest that it's working, it would certainly be merged promptly.

**Comment by SiriusLightning21** [comment]
I have now delete the Umbrel part in igniter.sh and add this.

# If an citadel, use docker, else call lncli directly. Also setup dependencies >
LNCLI="lncli"
if [ -d "$HOME/citadel" ] ; then
    LNCLI="docker exec -i lightning lncli"
    dependencies="cat jq"
fi

With this the build and send option will work perfect. Tested on Citadel 0.1.3.

But the connect part has these erros:
./igniter.sh: line 43: docker exec -i lightning lncli: command not found
./igniter.sh: line 41: docker exec -i lightning lncli: command not found

**Comment by RooSoft** [comment]
> But the connect part has these erros: ./igniter.sh: line 43: docker exec -i lightning lncli: command not found ./igniter.sh: line 41: docker exec -i lightning lncli: command not found

What happens if you just issue the `docker` command with no arguments?

**Comment by RooSoft** [comment]
> > But the connect part has these erros: ./igniter.sh: line 43: docker exec -i lightning lncli: command not found ./igniter.sh: line 41: docker exec -i lightning lncli: command not found
> 
> What happens if you just issue the `docker` command with no arguments?

In the same context as igniter, of course...

**Comment by SiriusLightning21** [comment]
> > > But the connect part has these erros: ./igniter.sh: line 43: docker exec -i lightning lncli: command not found ./igniter.sh: line 41: docker exec -i lightning lncli: command not found
> > 
> > 
> > What happens if you just issue the `docker` command with no arguments?
> 
> In the same context as igniter, of course...

I don´t know what and where I should change it.  In my config is this written.

line 41 is: ADDRESS=$($LNCLI getnodeinfo $KEY | grep \"addr\" |head -n 1| awk '{print $2}' |sed 's/"//g' )
line 43 is: $LNCLI connect $KEY@$ADDRESS

**Comment by RooSoft** [comment]
> I don´t know what and where I should change it. In my config is this written.

In the same shell you use the igniter script, simply type `docker` and see if docker answers... my guess is you'll get an error message instead.

**Comment by SiriusLightning21** [comment]
> > I don´t know what and where I should change it. In my config is this written.
> 
> In the same shell you use the igniter script, simply type `docker` and see if docker answers... my guess is you'll get an error message instead.

Ok I have a Folder this is called igniter where igniter.sh and igniter.conf is stored. In this folder I typed "docker". Docker answerd that I can use it with Options and Commands.
