### ISSUE TITLE
Integer fee breaks the script

### ISSUE THREAD

**Issue by giovannizotta** [RooSoft/igniter#4]
Hello, 
today I met a person who was having problems while running the script, and I think I've identified the cause.
On line 47, there is this instruction:
`FEE=${FEE:1:-4}`

This strips the `FEE` variable of the first character and of the last four. My guess is that this was made to remove the decimal digits that one can have in the Lightning Network. However, this person was having fees equivalent to **0**, with no decimal digits, and this was causing the script to crash.
I solved this by putting **-1** instead of **-4**, but a more sophisticated solution should be implemented.

**Comment by pgerstbach** [comment]
I just had the same issue.

**Comment by RooSoft** [comment]
Will check this out this week, thanks for reporting, very appreciated!

**Comment by RooSoft** [comment]
@sipsorcery, can you take a look at this, please? Looks like might be originating from [this pull request](https://github.com/RooSoft/igniter/pull/3/files).

**Comment by pgerstbach** [comment]
Thanks!
